from gl import RayTracer, color
from sphere import * 
from obj import Envmap, Texture
import random

# creación de materiales para reflexion y refraccion
mirror = Material(spec = 64, t = REFLECTIVE)
glass = Material(spec = 64, ior = 1.5, t= TRANSPARENT) 

# materiales con textura (Minecraft)
mcraft_chest = Material(texture = Texture('./textures/chest.bmp'))
mcraft_creeper = Material(texture = Texture('./textures/creeper.bmp'))
mcraft_creeperface = Material(texture = Texture('./textures/creeperface.bmp'))
mcraft_diamond = Material(texture = Texture('./textures/diamond.bmp'))
mcraft_dirt = Material(texture = Texture('./textures/dirt.bmp'))
mcraft_glowstone = Material(texture=Texture('./textures/glow3.bmp'))
mcraft_water = Material(texture = Texture('./textures/water.bmp'), t=REFLECTIVE) # reflectivo
mcraft_slime = Material(texture = Texture('./textures/slime.bmp'))
mcraft_stone = Material(texture = Texture('./textures/stone.bmp'))

# creamos espacio para renderizar
width = 512
height = 512
r = RayTracer(width, height)

# luces de distintos tipos
r.point_lights.append(PointLight(position = [2, 3, -9], intensity = 0.7))
r.point_lights.append(PointLight(position = [-2, 3, -9], intensity = 0.7))
r.point_lights.append(PointLight(position = [2, 3, -8], intensity = 0.1))
r.point_lights.append(PointLight(position = [-2, 3, -8], intensity = 0.1))
r.ambient_light = AmbientLight(strength = 0.2)

# environment map
r.env_map = Envmap('./envmaps/nolamps.bmp');

# objetos en la escena
## ENVIRONMENT ##
r.scene.append(Cube([-4, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, 3, -9], [1, 1, 1], mcraft_glowstone))
r.scene.append(Cube([-1, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, 3, -9], [1, 1, 1], mcraft_glowstone))
r.scene.append(Cube([3, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([4, 3, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([3, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([4, 2, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, 1, -9], [1, 1, 1], mcraft_diamond))
r.scene.append(Cube([3, 1, -9], [1, 1, 1], mcraft_diamond))
r.scene.append(Cube([4, 1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, 0, -9], [1, 1, 1], mcraft_diamond))
r.scene.append(Cube([3, 0, -9], [1, 1, 1], mcraft_diamond))
r.scene.append(Cube([4, 0, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([3, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([4, -1, -9], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, -1, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, -2, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, -2, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, -1, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, -1, -8], [1, 1, 1], mcraft_chest))
r.scene.append(Cube([0, -2, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, -2, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, -2, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([3, -1, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([4, -1, -8], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-4, -2, -7], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-3, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-2, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-1, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([0, -2, -7], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, -2, -7], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([3, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([4, -2, -7], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-3, -2, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-2, -3, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-1, -3, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([0, -2, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([1, -2, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([2, -2, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([3, -2, -6], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-3, -2, -5], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-2, -3, -5], [1, 1, 1], mcraft_water))
r.scene.append(Cube([-1, -3, -5], [1, 1, 1], mcraft_water))
r.scene.append(Cube([0, -3, -5], [1, 1, 1], mcraft_water))
r.scene.append(Cube([1, -2, -5], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([2, -3, -5], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([3, -2, -5], [1, 1, 1], mcraft_dirt))
r.scene.append(Cube([-3, -4, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-2, -3, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([-1, -3, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([0, -3, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([1, -3, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([2, -3, -4], [1, 1, 1], mcraft_stone))
r.scene.append(Cube([3, -3, -4], [1, 1, 1], mcraft_stone))

## MOBS ##
r.scene.append(Cube([2, -0.9, -7], [1.2, 1.2, 1.2], mcraft_slime))
r.scene.append(Cube([2, -1.2, -5.8], [0.6, 0.6, 0.6], mcraft_slime))
r.scene.append(Cube([1, -1.2, -7.5], [0.6, 0.6, 0.6], mcraft_slime))
r.scene.append(Cube([0.3, -1.2, -6.5], [0.6, 0.6, 0.6], mcraft_slime))
r.scene.append(Cube([-2, -1.3, -7], [1, 0.4, 0.4], mcraft_creeper))
r.scene.append(Cube([-2, -1.3, -7.6], [1, 0.4, 0.4], mcraft_creeper))
r.scene.append(Cube([-2, -0.6, -7.3], [0.8, 1, 0.4], mcraft_creeper))
r.scene.append(Cube([-2, 0.3, -7.4], [0.8, 0.8, 0.8], mcraft_creeperface))

# render
r.glRayTracingRender()

# generamos el output
r.glFinish('mobsatnight.bmp')
